-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 12:46:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` DEFAULT CHARACTER SET utf8 ;
USE `loja` ;

-- -----------------------------------------------------
-- Table `loja`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(15) NULL,
  `preco` DECIMAL(10,2) NULL,
  `tamanho` VARCHAR(3) NULL,
  `modelo` VARCHAR(15) NULL,
  `cor` VARCHAR(10) NULL,
  `quantidade` INT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NULL,
  `email` VARCHAR(35) NULL,
  `data_nascimento` DATE NULL,
  `senha` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `total` DECIMAL(10,5) NOT NULL,
  `data_cadastro` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_usuarios1_idx` (`usuario` ASC)  ,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC)  ,
  CONSTRAINT `fk_vendas_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `loja`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`itens_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`itens_vendas` (
  `produto` INT NOT NULL,
  `venda` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`produto`, `venda`),
  INDEX `fk_produtos_has_vendas_vendas1_idx` (`venda` ASC)  ,
  INDEX `fk_produtos_has_vendas_produtos1_idx` (`produto` ASC)  ,
  CONSTRAINT `fk_produtos_has_vendas_produtos1`
    FOREIGN KEY (`produto`)
    REFERENCES `loja`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_vendas_vendas1`
    FOREIGN KEY (`venda`)
    REFERENCES `loja`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`fornecedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`compras` (
  `id` INT NOT NULL,
  `fornecedor` INT NOT NULL,
  `data_cadastro` DATETIME NULL,
  INDEX `fk_usuarios_has_fornecedores_fornecedores1_idx` (`fornecedor` ASC)  ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuarios_has_fornecedores_fornecedores1`
    FOREIGN KEY (`fornecedor`)
    REFERENCES `loja`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`itens_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`itens_compra` (
  `produto` INT NOT NULL,
  `compra` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`produto`, `compra`),
  INDEX `fk_produtos_has_compras_fornecedores_compras_fornecedores1_idx` (`compra` ASC)  ,
  INDEX `fk_produtos_has_compras_fornecedores_produtos1_idx` (`produto` ASC)  ,
  CONSTRAINT `fk_produtos_has_compras_fornecedores_produtos1`
    FOREIGN KEY (`produto`)
    REFERENCES `loja`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_compras_fornecedores_compras_fornecedores1`
    FOREIGN KEY (`compra`)
    REFERENCES `loja`.`compras` (`fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
