-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 16:03:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loja` (
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `dominio` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Loja_cnpj` INT NOT NULL,
  PRIMARY KEY (`dominio`, `Loja_cnpj`),
  INDEX `fk_Site_Loja1_idx` (`Loja_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Site_Loja1`
    FOREIGN KEY (`Loja_cnpj`)
    REFERENCES `mydb`.`Loja` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `id_estoque` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `localização_produtos` VARCHAR(45) NULL,
  `Loja_cnpj` INT NOT NULL,
  PRIMARY KEY (`id_estoque`, `Loja_cnpj`),
  INDEX `fk_Estoque_Loja1_idx` (`Loja_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Loja1`
    FOREIGN KEY (`Loja_cnpj`)
    REFERENCES `mydb`.`Loja` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id_produto` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `preco` FLOAT NULL,
  `tamanho` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `Estoque_id_estoque` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `Estoque_id_estoque`),
  INDEX `fk_Produto_Estoque1_idx` (`Estoque_id_estoque` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Estoque1`
    FOREIGN KEY (`Estoque_id_estoque`)
    REFERENCES `mydb`.`Estoque` (`id_estoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Loja_cnpj` INT NOT NULL,
  PRIMARY KEY (`cnpj`, `Loja_cnpj`),
  INDEX `fk_Fornecedor_Loja1_idx` (`Loja_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_Loja1`
    FOREIGN KEY (`Loja_cnpj`)
    REFERENCES `mydb`.`Loja` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionarios` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `data_nascimento` DATETIME NULL,
  `endereço` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `Loja_cnpj` INT NOT NULL,
  `Estoque_id_estoque` INT NOT NULL,
  `Estoque_Loja_cnpj` INT NOT NULL,
  PRIMARY KEY (`cpf`, `Loja_cnpj`, `Estoque_id_estoque`, `Estoque_Loja_cnpj`),
  INDEX `fk_Funcionarios_Loja1_idx` (`Loja_cnpj` ASC) VISIBLE,
  INDEX `fk_Funcionarios_Estoque1_idx` (`Estoque_id_estoque` ASC, `Estoque_Loja_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionarios_Loja1`
    FOREIGN KEY (`Loja_cnpj`)
    REFERENCES `mydb`.`Loja` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionarios_Estoque1`
    FOREIGN KEY (`Estoque_id_estoque` , `Estoque_Loja_cnpj`)
    REFERENCES `mydb`.`Estoque` (`id_estoque` , `Loja_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `Site_dominio` INT NOT NULL,
  `endereço` INT NOT NULL,
  PRIMARY KEY (`cpf`, `Site_dominio`, `endereço`),
  INDEX `fk_Usuario_Site1_idx` (`Site_dominio` ASC, `endereço` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Site1`
    FOREIGN KEY (`Site_dominio` , `endereço`)
    REFERENCES `mydb`.`Site` (`dominio` , `Loja_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
