-- MySQL Script generated by MySQL Workbench
-- Sat Aug 24 16:47:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` DEFAULT CHARACTER SET utf8 ;
USE `loja` ;

-- -----------------------------------------------------
-- Table `loja`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`produtos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(15) NOT NULL,
  `preco` DECIMAL(13) NOT NULL,
  `tamanho` VARCHAR(3) NOT NULL,
  `modelo` VARCHAR(15) NOT NULL,
  `cor` VARCHAR(10) NOT NULL,
  `quantidade` INT NOT NULL,
  `descriao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(40) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  `data_nascimento` DATETIME NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`vendas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `usuarios` INT NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  `data_cadrastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `usuarios`),
  INDEX `fk_vendas_usuarios1_idx` (`usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_usuarios1`
    FOREIGN KEY (`usuarios`)
    REFERENCES `loja`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`itens_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`itens_vendas` (
  `produtos` INT NOT NULL,
  `vendas` INT NOT NULL,
  `itens_vendas` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`produtos`, `vendas`, `itens_vendas`),
  INDEX `fk_produtos_has_vendas_vendas1_idx` (`vendas` ASC, `itens_vendas` ASC) VISIBLE,
  INDEX `fk_produtos_has_vendas_produtos1_idx` (`produtos` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_has_vendas_produtos1`
    FOREIGN KEY (`produtos`)
    REFERENCES `loja`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_vendas_vendas1`
    FOREIGN KEY (`vendas` , `itens_vendas`)
    REFERENCES `loja`.`vendas` (`id` , `usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`fornecedores` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`compras_fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`compras_fornecedores` (
  `usuarios_id` INT NOT NULL,
  `fornecedores_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `fornecedores_id`),
  INDEX `fk_usuarios_has_fornecedores_fornecedores1_idx` (`fornecedores_id` ASC) VISIBLE,
  INDEX `fk_usuarios_has_fornecedores_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_fornecedores_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `loja`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_fornecedores_fornecedores1`
    FOREIGN KEY (`fornecedores_id`)
    REFERENCES `loja`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
